### ISSUE TITLE
Navigating to your Holopass profile URL allows you to follow yourself.

### ISSUE THREAD

**Issue by CyberiumShadow** [watsonindustries/holopass#6]
Steps to Reproduce:
- Go to your "My Pass"
- Copy Link
- Navigate to the copied link
- Select Follow

Expected Result:
You should not be able to follow yourself on Holopass.

Actual Result:
You are now following yourself on Holopass and this can be confirmed in the following list.

**Comment by DaniruKun** [comment]
Fixed during #8
